version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: night-market-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: night_market
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
